# Temporany file, will be updated in the future, this is not final config

version: '3'
services:
  backend:
    image: ./backend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_USER=your-db-user
    #   - DB_PASSWORD=your-db-password
    #   - DB_NAME=your-db-name

  ollama:
    image: ollama/ollama:latest
    ports:
      - 8000:8000
    volumes:
      - ./ollama:/app
    # environment:

  cassandradb:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
