# Temporary file, will be updated in the future, this is not final config
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - ollama
      - cassandradb

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/app
    # environment:

    #! Note: For open a cql cli use this command: docker exec -it <container_id> cqlsh
  cassandradb:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init.cql:/init/init.cql

volumes:
  cassandra_data:
